from application.models.util import *

class Main(Model):
   NameSorted       = PrimaryKeyField()
   Id               = TextField()
   NameRaw          = TextField()
   MolecularFormula = TextField()
   StructuralFormula= TextField()
   molecularWeight  = TextField()
   casNo            = TextField()
   Id2              = TextField()
   Id3              = TextField()
   Description      = TextField()
   BoilingPoint     = TextField()
   MeltingPoint     = TextField()
   VaporPressure    = TextField()
   SpecificGravity  = TextField()
   Flamable         = TextField()
   PhysicalDescription = TextField()
   Corrosive        = TextField()
   Hazardous        = TextField()
   Explosive        = TextField()
   Refrigerate      = TextField()
   #LastUpdated      = TextField()
   #ReservedText1    = TextField()
   Goggles          = TextField()
   Gloves           = TextField()
   State            = TextField()
   Respirator       = TextField()
   Comments         = TextField()
   #Warn             = TextField()
   Nfpa_Health      = TextField()
   Nfpa_Flamable    = TextField()
   Nfpa_Reactive    = TextField()
   Nfpa_Specific    = TextField()
   Radioactive      = TextField()
   #hazardInstuctions= TextField()
   #MSDS_ReviewDate  = TextField()
   #Spill_Control    = TextField()
   #Label_Text       = TextField()
   #DOT_Code         = TextField()
   #isSara3          = TextField()
   #isTier2          = TextField()
   #isFormR          = TextField()
   #UserCheck1       = TextField()
   #UserCheck2       = TextField()
   Carcinogenic     = TextField()
   Organic          = TextField()
   Inorganic        = TextField()
   #Biohazardous     = TextField()
   #DateLastUpdated  = TextField()
   #WhoLastUpdated   = TextField()
   #ChemType         = TextField()
   #DOT_TEXT         = TextField()

   class Meta:
      database = getDB("cispro", "static")
