selections: &zeroThruFour
   - "0"
   - "1"
   - "2"
   - "3"
   - "4"

otherHazards: &otherHazards
   - "None"
   - "OX (Oxidizer)"
   - "Water Reactive"
   - "SA (Simple Asphyxiant Gas)"
   
# Add New Chemical form
pictograms:
  # Pictograms found @ https://www.osha.gov/dsg/hazcom/pictograms/
    - pict: "/static/pictograms/corrosivePict.png"
      id: "corrosivePict"
      type: "checkbox"
      alt: "Corrosion"
    - pict: "/static/pictograms/environmentalPict.png"
      id: "envPict"
      type: "checkbox"
      alt: "Environmental"
    - pict: "/static/pictograms/exclamationPict.png"
      id: "emPict"
      type: "checkbox"
      alt: "Exclamation Mark"
    - pict: "/static/pictograms/flamePict.png"
      id: "flamePict"
      type: "checkbox"
      alt: "Flame"
    - pict: "/static/pictograms/gasCylinderPict.png"
      id: "gcPict"
      type: "checkbox"
      alt: "Gas Cylinder"
    - pict: "/static/pictograms/healthPict.png"
      id: "hhPict"
      type: "checkbox"
      alt: "Health Hazard"
    - pict: "/static/pictograms/oxidizerPict.png"
      id: "oxidizerPict"
      type: "checkbox"
      alt: "Flame Over Circle"
    - pict: "/static/pictograms/toxicPict.png"
      id: "toxicPict"
      type: "checkbox"
      alt: "Skull and Crossbones"
    - pict: "/static/pictograms/explPict.png"
      id: "expPict"
      type: "checkbox"
      alt: "Explosion"

HMIS:
   - name: "Health"
     id: "hmisHealth"
     type: "dropdown"
     color: "blue"
     text: "#FFF"
     selections: *zeroThruFour
   - name: "Flammability"
     id: "hmisFlammable"
     type: "dropdown"
     color: "red"
     text: "#FFF"
     selections: *zeroThruFour
   - name: "Physical Hazard"
     id: "hmisPhysical"
     type: "dropdown"
     color: "orange"
     text: "#FFF"
     selections: *zeroThruFour
   - name: "Personal Protection"
     id: "hmisPPE"
     type: "dropdown"
     color: "white"
     selections:
       - "A"
       - "B"
       - "C"
       - "D"
       - "E"
       - "F"
       - "G"
       - "H"
       - "I"
       - "J"
       - "K"

NFPAdiamond:
  # Used to build the selection form for the NFPA "Fire Diamond"
    - section: "Flammability"
      id: "flammable"
      type: "dropdown"
      selections: *zeroThruFour
    - section: "Instability/Reactivity"
      id: "reactive"
      type: "dropdown"
      selections: *zeroThruFour
    - section: "Health"
      id: "healthHazard"
      type: "dropdown"
      selections: *zeroThruFour
    - section: "Special"
      id: "other"
      type: "dropdown"
      selections: *otherHazards

addChemInputs:
    - name: "Name"
      id: "name"
      type: "text"
      placeholder: "Chemical Name"
      special: "required"
    - name: "Cas Number"
      id: "casNum"
      type: "text"
      placeholder: "Cas Number"
    - name: "Formula"
      id: "formula"
      type: "text"
      placeholder: "Chemical Formula"
    - name: "Flash Point"
      id: "flashPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Boiling Point"
      id: "boilPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Storage Temp"
      id: "storageTemp"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Safety Data Sheet Link"
      id: "sdsLink"
      type: "text"
      placeholder: "SDS Link"
    - name: "Description"
      id: "description"
      type: "text"
      placeholder: "Description of Chemical"

timeSensitive:
    - name: "Pressure Former"
      id: "pressureFormer"
      type: "checkbox"
    - name: "Requires Stabalizer"
      id: "reqStabalizer"
      type: "checkbox"
    - name: "Peroxide Former"
      id: "peroxideFormer"
      type: "checkbox"
    - name: "Forms Toxins Over Time"
      id: "toxicFormation"
      type: "checkbox"

addChemChecks:
    - name: "Carcinogen"
      id: "carcinogen"
      type: "checkbox"
    - name: "P-List Acute Toxicity"
      id: "pListAcute"
      type: "checkbox"

addChemDropdowns:
    - name: "Primary Hazard"
      id: "primaryHazard"
      type: "dropdown"
      special: "required"
      selections:
        - "Flammable"
          # color: "Red"
        - "Flammable Solid"
          # color: "Copper"
        - "Health Hazard"
          # color: "Blue"
        - "Organic Acid"
          # color: "Lavender"
        - "Inorganic Acid"
          # color: "Rose"
        - "Base"
          # color: "Green"
        - "Oxidizer"
          # color: "Yellow"
        - "Reactive"
          # color: "Orange"
        - "General Hazard" #May need to update
          # color: "None"
    - name: "Structure"
      id: "structure"
      type: "dropdown"
      special: "required"
      selections:
        - "Organic"
        - "Inorganic"
    - name: "State"
      id: "state"
      type: "dropdown"
      special: "required"
      selections:
        - "Solid"
        - "Liquid"
        - "Gas"
